spring.application.name=demo

# Configuração do PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/pagaai-mobile
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver


#configuração do Hibernete
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect